// Build-time cover art fetch: SteamGridDB -> src/assets/covers/ (committed).
//
//   npm run covers            resolve anything not already downloaded
//   npm run covers -- --force re-resolve everything
//   npm run covers -- --dry   report resolutions without downloading
//
// Downloading rather than hotlinking keeps the deployed page static and self
// contained: no third-party request at view time, and art can't vanish when
// someone reorganises a CDN.
//
// Every resolution is printed with the name SteamGridDB actually matched, so a
// wrong match is visible immediately and can be corrected by adding an entry
// to src/data/cover-overrides.js.

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from "node:fs";
import { setTimeout as sleep } from "node:timers/promises";
import { search, grids, pickBest, pickGame, download, EXT_BY_MIME } from "./lib/steamgriddb.js";
import { COVER_OVERRIDES, normalizeTitle, slugify } from "../src/data/cover-overrides.js";

const ROOT = new URL("..", import.meta.url);
const COVER_DIR = new URL("src/assets/covers/", ROOT);
const MANUAL_DIR = new URL("src/assets/covers/manual/", ROOT);
const GENERATED = new URL("src/data/covers.generated.js", ROOT);

const force = process.argv.includes("--force");
const dryRun = process.argv.includes("--dry");

const games = JSON.parse(readFileSync(new URL("src/data/games.json", ROOT), "utf8"));

mkdirSync(COVER_DIR, { recursive: true });
mkdirSync(MANUAL_DIR, { recursive: true });

const existing = new Map(
  readdirSync(COVER_DIR, { withFileTypes: true })
    .filter((e) => e.isFile())
    .map((e) => [e.name.replace(/\.[^.]+$/, ""), e.name])
);

// One row per distinct title; DELTARUNE's three chapters share one lookup.
const titles = [...new Set(games.games.map((g) => g.title))];

const resolved = new Map();
const failures = [];
let fetched = 0;

for (const title of titles) {
  const slug = slugify(title);
  const override = COVER_OVERRIDES[title] ?? {};

  if (override.file) {
    resolved.set(slug, { file: `manual/${override.file}`, via: "manual" });
    continue;
  }

  if (!force && existing.has(slug)) {
    resolved.set(slug, { file: existing.get(slug), via: "cached" });
    continue;
  }

  const term = override.search ?? normalizeTitle(title);

  try {
    let gameId = override.id;
    let matchedName = override.id ? `id:${override.id}` : null;

    if (!gameId) {
      const hits = await search(term);
      const game = pickGame(hits, term);
      if (!game) {
        failures.push({ title, term, reason: "no search result" });
        continue;
      }
      gameId = game.id;
      matchedName = game.name;
    }

    const art = await grids(gameId);
    const best = pickBest(art);
    if (!best) {
      failures.push({ title, term, reason: `no landscape art (matched "${matchedName}")` });
      continue;
    }

    const ext = EXT_BY_MIME[best.mime] ?? "png";
    const file = `${slug}.${ext}`;

    if (!dryRun) {
      writeFileSync(new URL(file, COVER_DIR), await download(best.url));
      fetched++;
    }

    resolved.set(slug, { file, via: matchedName });
    const flag = matchedName.toLowerCase() === term.toLowerCase() ? " " : "~";
    console.log(`${flag} ${title.padEnd(46)} -> ${matchedName}`);

    // The API is generous but this is a background chore; stay polite.
    await sleep(140);
  } catch (err) {
    failures.push({ title, term, reason: err.message });
  }
}

// Emit explicit imports rather than relying on require.context, so the module
// graph stays statically analysable and webpack hashes each asset normally.
if (!dryRun) {
  const entries = [...resolved.entries()].sort(([a], [b]) => a.localeCompare(b));
  const lines = [
    "// GENERATED by scripts/fetch-covers.js - do not edit.",
    "// Regenerate with `npm run covers`.",
    "",
    ...entries.map(([slug, r], i) => `import c${i} from "../assets/covers/${r.file}";`),
    "",
    "export const COVERS = {",
    ...entries.map(([slug], i) => `  ${JSON.stringify(slug)}: c${i},`),
    "};",
    "",
  ];
  writeFileSync(GENERATED, lines.join("\n"));
}

console.log(`\nresolved ${resolved.size} of ${titles.length} titles` + (dryRun ? " (dry run)" : `, downloaded ${fetched}`));

if (failures.length) {
  console.warn(`\n${failures.length} unresolved - add an override in src/data/cover-overrides.js:`);
  for (const f of failures) console.warn(`  ${f.title}  [searched "${f.term}"]  ${f.reason}`);
}
